version: "3.6"
services:
  # mariadb:
  #   build: ./requirements/mariadb
  #   image: mariadb
  #   container_name: mariadb-container

  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    container_name: wordpress
    volumes:
      - wordpress:/var/www
    ports:
      - "9000:9000"

  nginx:
    build: ./requirements/nginx
    image: nginx
    container_name: nginx
    # depends_on:
    #   - wordpress
    volumes:
      - wordpress:/var/www
    ports:
      - "80:80"
      - "443:443"

volumes:
    wordpress:
    DB: