version: "3.6"
services:
  # mariadb:
  #   build: ./requirements/mariadb
  #   image: mariadb
  #   container_name: mariadb-container

  # wordpress:
  #   build: ./requirements/wordpress
  #   image: wordpress
  #   container_name: wordpress-container
  #   volumes:
  #     - ./wordpress:/var/www/html

  nginx:
    build: ./requirements/nginx
    image: nginx
    container_name: nginx-container
    volumes:
      - wordpress:/var/www/html
    ports:
      - "80:80"
      - "443:443"

volumes:
    wordpress:
    # DB: