version: "3.6"
services:
  adminer:
    build: ./requirements/bonus/adminer
    image: adminer
    container_name: adminer
    networks:
      inception:
        ipv4_address: 192.12.0.5
    ports:
      - "9000:9000"
      
  mariadb:
    build: ./requirements/mariadb
    image: mariadb:1
    container_name: mariadb
    networks:
      inception:
          ipv4_address: 192.12.0.4
    volumes:
      - DB:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "inception"
      MYSQL_USER: "mouras"
      MYSQL_PASSWORD: "mouras"
    expose:
      - "3306"

  wordpress:
    build: ./requirements/wordpress
    image: wordpress:1
    container_name: wordpress
    environment:
      MYSQL_DATABASE: "inception"
      MYSQL_USER: "mouras"
      MYSQL_PASSWORD: "mouras"
      WP_USER: "ahshly"
      WP_USER_PASSWORD: "ahshly@@"
      WP_ADMIN_USER: "test"
      WP_ADMIN_USER_PASSWORD: "test@@"
    volumes:
      - wordpress:/var/www
    networks:
      inception:
          ipv4_address: 192.12.0.3
    
    expose:
      - "9000"

  nginx:
    build: ./requirements/nginx
    image: nginx:1
    container_name: nginx
    # depends_on:
    #   - wordpress
    volumes:
      - wordpress:/var/www
    ports:
      - "443:443"
    networks:
      inception:
          ipv4_address: 192.12.0.2

volumes:
    wordpress:
      name: wordpress
    DB:
      name: DB

networks:
  inception:
    name: inception_network
    driver: bridge
    ipam:
      config:
        - subnet: 192.12.0.0/16
  

# GRANT ALL PRIVILEGES ON inception.* TO 'user'@'192.12.0.3';